version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    groups:
      aws-sdk:
        patterns:
          - "aws-*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
