# Builds binaries and uploads them to a GitHub release when a v* tag is pushed.
name: Publish release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create-release
        uses: softprops/action-gh-release@v1
  build:
    name: Build release binaries
    runs-on: ${{ matrix.runner-os }}
    needs: create-release
    strategy:
      matrix:
        include:
          # Match Go/cmgr convention for suffixes
          - runner-os: ubuntu-20.04
            rustc-target: "x86_64-unknown-linux-gnu"
            binary-suffix: "linux_amd64"
          - runner-os: ubuntu-20.04
            rustc-target: "aarch64-unknown-linux-gnu"
            binary-suffix: "linux_arm64"
          - runner-os: macos-11
            rustc-target: "x86_64-apple-darwin"
            binary-suffix: "darwin_amd64"
          - runner-os: macos-11
            rustc-target: "aarch64-apple-darwin"
            binary-suffix: "darwin_arm64"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.rustc-target }}
          override: true
          profile: minimal
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: "--release"
      - name: Create tarball
        run: |
          mkdir out
          cp target/release/cmgr-artifact-server out/
          cp README.md out/
          cd out && tar czf cmgr-artifact-server_${suffix}.tar.gz *
        env:
          suffix: ${{ matrix.binary-suffix }}
      - name: Upload tarball
        uses: softprops/action-gh-release@v1
        with:
          files: out/*.tar.gz
